# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/illia/desktop/proj/@c++/retroengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/illia/desktop/proj/@c++/retroengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.27.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.27.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.27.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.27.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.27.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.27.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/illia/desktop/proj/@c++/retroengine/CMakeFiles /Users/illia/desktop/proj/@c++/retroengine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/illia/desktop/proj/@c++/retroengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named retroengine

# Build rule for target.
retroengine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 retroengine
.PHONY : retroengine

# fast build rule for target.
retroengine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/build
.PHONY : retroengine/fast

#=============================================================================
# Target rules for targets named sandbox

# Build rule for target.
sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sandbox
.PHONY : sandbox

# fast build rule for target.
sandbox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/build
.PHONY : sandbox/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/GLFW/CMakeFiles/uninstall.dir/build.make lib/GLFW/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/GLFW/src/CMakeFiles/glfw.dir/build.make lib/GLFW/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/GLFW/src/CMakeFiles/update_mappings.dir/build.make lib/GLFW/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

lib/glad/src/glad.o: lib/glad/src/glad.c.o
.PHONY : lib/glad/src/glad.o

# target to build an object file
lib/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/glad/src/glad.c.o
.PHONY : lib/glad/src/glad.c.o

lib/glad/src/glad.i: lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.i

# target to preprocess a source file
lib/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.c.i

lib/glad/src/glad.s: lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.s

# target to generate assembly for a file
lib/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.c.s

lib/imgui/imgui.o: lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.o

# target to build an object file
lib/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.cpp.o

lib/imgui/imgui.i: lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.i

# target to preprocess a source file
lib/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.cpp.i

lib/imgui/imgui.s: lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.s

# target to generate assembly for a file
lib/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.cpp.s

lib/imgui/imgui_demo.o: lib/imgui/imgui_demo.cpp.o
.PHONY : lib/imgui/imgui_demo.o

# target to build an object file
lib/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_demo.cpp.o
.PHONY : lib/imgui/imgui_demo.cpp.o

lib/imgui/imgui_demo.i: lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.i

# target to preprocess a source file
lib/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.cpp.i

lib/imgui/imgui_demo.s: lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.s

# target to generate assembly for a file
lib/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.cpp.s

lib/imgui/imgui_draw.o: lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.o

# target to build an object file
lib/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.cpp.o

lib/imgui/imgui_draw.i: lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.i

# target to preprocess a source file
lib/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.cpp.i

lib/imgui/imgui_draw.s: lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.s

# target to generate assembly for a file
lib/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.cpp.s

lib/imgui/imgui_tables.o: lib/imgui/imgui_tables.cpp.o
.PHONY : lib/imgui/imgui_tables.o

# target to build an object file
lib/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_tables.cpp.o
.PHONY : lib/imgui/imgui_tables.cpp.o

lib/imgui/imgui_tables.i: lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.i

# target to preprocess a source file
lib/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.cpp.i

lib/imgui/imgui_tables.s: lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.s

# target to generate assembly for a file
lib/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.cpp.s

lib/imgui/imgui_widgets.o: lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.o

# target to build an object file
lib/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.cpp.o

lib/imgui/imgui_widgets.i: lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.i

# target to preprocess a source file
lib/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.cpp.i

lib/imgui/imgui_widgets.s: lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.s

# target to generate assembly for a file
lib/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.cpp.s

src/app.o: src/app.cc.o
.PHONY : src/app.o

# target to build an object file
src/app.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/app.cc.o
.PHONY : src/app.cc.o

src/app.i: src/app.cc.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/app.cc.i
.PHONY : src/app.cc.i

src/app.s: src/app.cc.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/app.cc.s
.PHONY : src/app.cc.s

src/imgui/imgui_build.o: src/imgui/imgui_build.cc.o
.PHONY : src/imgui/imgui_build.o

# target to build an object file
src/imgui/imgui_build.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/imgui/imgui_build.cc.o
.PHONY : src/imgui/imgui_build.cc.o

src/imgui/imgui_build.i: src/imgui/imgui_build.cc.i
.PHONY : src/imgui/imgui_build.i

# target to preprocess a source file
src/imgui/imgui_build.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/imgui/imgui_build.cc.i
.PHONY : src/imgui/imgui_build.cc.i

src/imgui/imgui_build.s: src/imgui/imgui_build.cc.s
.PHONY : src/imgui/imgui_build.s

# target to generate assembly for a file
src/imgui/imgui_build.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/imgui/imgui_build.cc.s
.PHONY : src/imgui/imgui_build.cc.s

src/imgui/imgui_layer.o: src/imgui/imgui_layer.cc.o
.PHONY : src/imgui/imgui_layer.o

# target to build an object file
src/imgui/imgui_layer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/imgui/imgui_layer.cc.o
.PHONY : src/imgui/imgui_layer.cc.o

src/imgui/imgui_layer.i: src/imgui/imgui_layer.cc.i
.PHONY : src/imgui/imgui_layer.i

# target to preprocess a source file
src/imgui/imgui_layer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/imgui/imgui_layer.cc.i
.PHONY : src/imgui/imgui_layer.cc.i

src/imgui/imgui_layer.s: src/imgui/imgui_layer.cc.s
.PHONY : src/imgui/imgui_layer.s

# target to generate assembly for a file
src/imgui/imgui_layer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/imgui/imgui_layer.cc.s
.PHONY : src/imgui/imgui_layer.cc.s

src/layer.o: src/layer.cc.o
.PHONY : src/layer.o

# target to build an object file
src/layer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/layer.cc.o
.PHONY : src/layer.cc.o

src/layer.i: src/layer.cc.i
.PHONY : src/layer.i

# target to preprocess a source file
src/layer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/layer.cc.i
.PHONY : src/layer.cc.i

src/layer.s: src/layer.cc.s
.PHONY : src/layer.s

# target to generate assembly for a file
src/layer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/layer.cc.s
.PHONY : src/layer.cc.s

src/layer_stack.o: src/layer_stack.cc.o
.PHONY : src/layer_stack.o

# target to build an object file
src/layer_stack.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/layer_stack.cc.o
.PHONY : src/layer_stack.cc.o

src/layer_stack.i: src/layer_stack.cc.i
.PHONY : src/layer_stack.i

# target to preprocess a source file
src/layer_stack.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/layer_stack.cc.i
.PHONY : src/layer_stack.cc.i

src/layer_stack.s: src/layer_stack.cc.s
.PHONY : src/layer_stack.s

# target to generate assembly for a file
src/layer_stack.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/layer_stack.cc.s
.PHONY : src/layer_stack.cc.s

src/logging.o: src/logging.cc.o
.PHONY : src/logging.o

# target to build an object file
src/logging.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/logging.cc.o
.PHONY : src/logging.cc.o

src/logging.i: src/logging.cc.i
.PHONY : src/logging.i

# target to preprocess a source file
src/logging.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/logging.cc.i
.PHONY : src/logging.cc.i

src/logging.s: src/logging.cc.s
.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/logging.cc.s
.PHONY : src/logging.cc.s

src/pinp.o: src/pinp.cc.o
.PHONY : src/pinp.o

# target to build an object file
src/pinp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/pinp.cc.o
.PHONY : src/pinp.cc.o

src/pinp.i: src/pinp.cc.i
.PHONY : src/pinp.i

# target to preprocess a source file
src/pinp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/pinp.cc.i
.PHONY : src/pinp.cc.i

src/pinp.s: src/pinp.cc.s
.PHONY : src/pinp.s

# target to generate assembly for a file
src/pinp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/pinp.cc.s
.PHONY : src/pinp.cc.s

src/pwin.o: src/pwin.cc.o
.PHONY : src/pwin.o

# target to build an object file
src/pwin.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/pwin.cc.o
.PHONY : src/pwin.cc.o

src/pwin.i: src/pwin.cc.i
.PHONY : src/pwin.i

# target to preprocess a source file
src/pwin.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/pwin.cc.i
.PHONY : src/pwin.cc.i

src/pwin.s: src/pwin.cc.s
.PHONY : src/pwin.s

# target to generate assembly for a file
src/pwin.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/pwin.cc.s
.PHONY : src/pwin.cc.s

src/render/array.o: src/render/array.cc.o
.PHONY : src/render/array.o

# target to build an object file
src/render/array.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/array.cc.o
.PHONY : src/render/array.cc.o

src/render/array.i: src/render/array.cc.i
.PHONY : src/render/array.i

# target to preprocess a source file
src/render/array.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/array.cc.i
.PHONY : src/render/array.cc.i

src/render/array.s: src/render/array.cc.s
.PHONY : src/render/array.s

# target to generate assembly for a file
src/render/array.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/array.cc.s
.PHONY : src/render/array.cc.s

src/render/buf.o: src/render/buf.cc.o
.PHONY : src/render/buf.o

# target to build an object file
src/render/buf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/buf.cc.o
.PHONY : src/render/buf.cc.o

src/render/buf.i: src/render/buf.cc.i
.PHONY : src/render/buf.i

# target to preprocess a source file
src/render/buf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/buf.cc.i
.PHONY : src/render/buf.cc.i

src/render/buf.s: src/render/buf.cc.s
.PHONY : src/render/buf.s

# target to generate assembly for a file
src/render/buf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/buf.cc.s
.PHONY : src/render/buf.cc.s

src/render/cam/orthographic.o: src/render/cam/orthographic.cc.o
.PHONY : src/render/cam/orthographic.o

# target to build an object file
src/render/cam/orthographic.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/cam/orthographic.cc.o
.PHONY : src/render/cam/orthographic.cc.o

src/render/cam/orthographic.i: src/render/cam/orthographic.cc.i
.PHONY : src/render/cam/orthographic.i

# target to preprocess a source file
src/render/cam/orthographic.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/cam/orthographic.cc.i
.PHONY : src/render/cam/orthographic.cc.i

src/render/cam/orthographic.s: src/render/cam/orthographic.cc.s
.PHONY : src/render/cam/orthographic.s

# target to generate assembly for a file
src/render/cam/orthographic.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/cam/orthographic.cc.s
.PHONY : src/render/cam/orthographic.cc.s

src/render/opengl/opengl_array.o: src/render/opengl/opengl_array.cc.o
.PHONY : src/render/opengl/opengl_array.o

# target to build an object file
src/render/opengl/opengl_array.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_array.cc.o
.PHONY : src/render/opengl/opengl_array.cc.o

src/render/opengl/opengl_array.i: src/render/opengl/opengl_array.cc.i
.PHONY : src/render/opengl/opengl_array.i

# target to preprocess a source file
src/render/opengl/opengl_array.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_array.cc.i
.PHONY : src/render/opengl/opengl_array.cc.i

src/render/opengl/opengl_array.s: src/render/opengl/opengl_array.cc.s
.PHONY : src/render/opengl/opengl_array.s

# target to generate assembly for a file
src/render/opengl/opengl_array.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_array.cc.s
.PHONY : src/render/opengl/opengl_array.cc.s

src/render/opengl/opengl_buf.o: src/render/opengl/opengl_buf.cc.o
.PHONY : src/render/opengl/opengl_buf.o

# target to build an object file
src/render/opengl/opengl_buf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_buf.cc.o
.PHONY : src/render/opengl/opengl_buf.cc.o

src/render/opengl/opengl_buf.i: src/render/opengl/opengl_buf.cc.i
.PHONY : src/render/opengl/opengl_buf.i

# target to preprocess a source file
src/render/opengl/opengl_buf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_buf.cc.i
.PHONY : src/render/opengl/opengl_buf.cc.i

src/render/opengl/opengl_buf.s: src/render/opengl/opengl_buf.cc.s
.PHONY : src/render/opengl/opengl_buf.s

# target to generate assembly for a file
src/render/opengl/opengl_buf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_buf.cc.s
.PHONY : src/render/opengl/opengl_buf.cc.s

src/render/opengl/opengl_render_api.o: src/render/opengl/opengl_render_api.cc.o
.PHONY : src/render/opengl/opengl_render_api.o

# target to build an object file
src/render/opengl/opengl_render_api.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_render_api.cc.o
.PHONY : src/render/opengl/opengl_render_api.cc.o

src/render/opengl/opengl_render_api.i: src/render/opengl/opengl_render_api.cc.i
.PHONY : src/render/opengl/opengl_render_api.i

# target to preprocess a source file
src/render/opengl/opengl_render_api.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_render_api.cc.i
.PHONY : src/render/opengl/opengl_render_api.cc.i

src/render/opengl/opengl_render_api.s: src/render/opengl/opengl_render_api.cc.s
.PHONY : src/render/opengl/opengl_render_api.s

# target to generate assembly for a file
src/render/opengl/opengl_render_api.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_render_api.cc.s
.PHONY : src/render/opengl/opengl_render_api.cc.s

src/render/opengl/opengl_render_context.o: src/render/opengl/opengl_render_context.cc.o
.PHONY : src/render/opengl/opengl_render_context.o

# target to build an object file
src/render/opengl/opengl_render_context.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_render_context.cc.o
.PHONY : src/render/opengl/opengl_render_context.cc.o

src/render/opengl/opengl_render_context.i: src/render/opengl/opengl_render_context.cc.i
.PHONY : src/render/opengl/opengl_render_context.i

# target to preprocess a source file
src/render/opengl/opengl_render_context.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_render_context.cc.i
.PHONY : src/render/opengl/opengl_render_context.cc.i

src/render/opengl/opengl_render_context.s: src/render/opengl/opengl_render_context.cc.s
.PHONY : src/render/opengl/opengl_render_context.s

# target to generate assembly for a file
src/render/opengl/opengl_render_context.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/opengl/opengl_render_context.cc.s
.PHONY : src/render/opengl/opengl_render_context.cc.s

src/render/render_api.o: src/render/render_api.cc.o
.PHONY : src/render/render_api.o

# target to build an object file
src/render/render_api.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/render_api.cc.o
.PHONY : src/render/render_api.cc.o

src/render/render_api.i: src/render/render_api.cc.i
.PHONY : src/render/render_api.i

# target to preprocess a source file
src/render/render_api.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/render_api.cc.i
.PHONY : src/render/render_api.cc.i

src/render/render_api.s: src/render/render_api.cc.s
.PHONY : src/render/render_api.s

# target to generate assembly for a file
src/render/render_api.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/render_api.cc.s
.PHONY : src/render/render_api.cc.s

src/render/render_utils.o: src/render/render_utils.cc.o
.PHONY : src/render/render_utils.o

# target to build an object file
src/render/render_utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/render_utils.cc.o
.PHONY : src/render/render_utils.cc.o

src/render/render_utils.i: src/render/render_utils.cc.i
.PHONY : src/render/render_utils.i

# target to preprocess a source file
src/render/render_utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/render_utils.cc.i
.PHONY : src/render/render_utils.cc.i

src/render/render_utils.s: src/render/render_utils.cc.s
.PHONY : src/render/render_utils.s

# target to generate assembly for a file
src/render/render_utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/render_utils.cc.s
.PHONY : src/render/render_utils.cc.s

src/render/renderer.o: src/render/renderer.cc.o
.PHONY : src/render/renderer.o

# target to build an object file
src/render/renderer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/renderer.cc.o
.PHONY : src/render/renderer.cc.o

src/render/renderer.i: src/render/renderer.cc.i
.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/renderer.cc.i
.PHONY : src/render/renderer.cc.i

src/render/renderer.s: src/render/renderer.cc.s
.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/renderer.cc.s
.PHONY : src/render/renderer.cc.s

src/render/shader.o: src/render/shader.cc.o
.PHONY : src/render/shader.o

# target to build an object file
src/render/shader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/shader.cc.o
.PHONY : src/render/shader.cc.o

src/render/shader.i: src/render/shader.cc.i
.PHONY : src/render/shader.i

# target to preprocess a source file
src/render/shader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/shader.cc.i
.PHONY : src/render/shader.cc.i

src/render/shader.s: src/render/shader.cc.s
.PHONY : src/render/shader.s

# target to generate assembly for a file
src/render/shader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retroengine.dir/build.make CMakeFiles/retroengine.dir/src/render/shader.cc.s
.PHONY : src/render/shader.cc.s

src/sandbox/sandbox_app.o: src/sandbox/sandbox_app.cc.o
.PHONY : src/sandbox/sandbox_app.o

# target to build an object file
src/sandbox/sandbox_app.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/src/sandbox/sandbox_app.cc.o
.PHONY : src/sandbox/sandbox_app.cc.o

src/sandbox/sandbox_app.i: src/sandbox/sandbox_app.cc.i
.PHONY : src/sandbox/sandbox_app.i

# target to preprocess a source file
src/sandbox/sandbox_app.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/src/sandbox/sandbox_app.cc.i
.PHONY : src/sandbox/sandbox_app.cc.i

src/sandbox/sandbox_app.s: src/sandbox/sandbox_app.cc.s
.PHONY : src/sandbox/sandbox_app.s

# target to generate assembly for a file
src/sandbox/sandbox_app.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/src/sandbox/sandbox_app.cc.s
.PHONY : src/sandbox/sandbox_app.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... glfw"
	@echo "... retroengine"
	@echo "... sandbox"
	@echo "... lib/glad/src/glad.o"
	@echo "... lib/glad/src/glad.i"
	@echo "... lib/glad/src/glad.s"
	@echo "... lib/imgui/imgui.o"
	@echo "... lib/imgui/imgui.i"
	@echo "... lib/imgui/imgui.s"
	@echo "... lib/imgui/imgui_demo.o"
	@echo "... lib/imgui/imgui_demo.i"
	@echo "... lib/imgui/imgui_demo.s"
	@echo "... lib/imgui/imgui_draw.o"
	@echo "... lib/imgui/imgui_draw.i"
	@echo "... lib/imgui/imgui_draw.s"
	@echo "... lib/imgui/imgui_tables.o"
	@echo "... lib/imgui/imgui_tables.i"
	@echo "... lib/imgui/imgui_tables.s"
	@echo "... lib/imgui/imgui_widgets.o"
	@echo "... lib/imgui/imgui_widgets.i"
	@echo "... lib/imgui/imgui_widgets.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/imgui/imgui_build.o"
	@echo "... src/imgui/imgui_build.i"
	@echo "... src/imgui/imgui_build.s"
	@echo "... src/imgui/imgui_layer.o"
	@echo "... src/imgui/imgui_layer.i"
	@echo "... src/imgui/imgui_layer.s"
	@echo "... src/layer.o"
	@echo "... src/layer.i"
	@echo "... src/layer.s"
	@echo "... src/layer_stack.o"
	@echo "... src/layer_stack.i"
	@echo "... src/layer_stack.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/pinp.o"
	@echo "... src/pinp.i"
	@echo "... src/pinp.s"
	@echo "... src/pwin.o"
	@echo "... src/pwin.i"
	@echo "... src/pwin.s"
	@echo "... src/render/array.o"
	@echo "... src/render/array.i"
	@echo "... src/render/array.s"
	@echo "... src/render/buf.o"
	@echo "... src/render/buf.i"
	@echo "... src/render/buf.s"
	@echo "... src/render/cam/orthographic.o"
	@echo "... src/render/cam/orthographic.i"
	@echo "... src/render/cam/orthographic.s"
	@echo "... src/render/opengl/opengl_array.o"
	@echo "... src/render/opengl/opengl_array.i"
	@echo "... src/render/opengl/opengl_array.s"
	@echo "... src/render/opengl/opengl_buf.o"
	@echo "... src/render/opengl/opengl_buf.i"
	@echo "... src/render/opengl/opengl_buf.s"
	@echo "... src/render/opengl/opengl_render_api.o"
	@echo "... src/render/opengl/opengl_render_api.i"
	@echo "... src/render/opengl/opengl_render_api.s"
	@echo "... src/render/opengl/opengl_render_context.o"
	@echo "... src/render/opengl/opengl_render_context.i"
	@echo "... src/render/opengl/opengl_render_context.s"
	@echo "... src/render/render_api.o"
	@echo "... src/render/render_api.i"
	@echo "... src/render/render_api.s"
	@echo "... src/render/render_utils.o"
	@echo "... src/render/render_utils.i"
	@echo "... src/render/render_utils.s"
	@echo "... src/render/renderer.o"
	@echo "... src/render/renderer.i"
	@echo "... src/render/renderer.s"
	@echo "... src/render/shader.o"
	@echo "... src/render/shader.i"
	@echo "... src/render/shader.s"
	@echo "... src/sandbox/sandbox_app.o"
	@echo "... src/sandbox/sandbox_app.i"
	@echo "... src/sandbox/sandbox_app.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

